image: maven:3.8.3-openjdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  DOCKER_REGISTRY: <your-docker-registry>
  DOCKER_IMAGE_NAME: <your-docker-image-name>
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar

# deploy:
#   stage: deploy
#   script:
#     - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY
#     - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
#     - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG